version: '3.1'
services:
    # broker:
    #     image: emqx/emqx
    #     container_name: broker
    #     restart: always
    #     ports:
    #         - "1883:1883"
    #         - "8083:8083"
    #         - "8883:8883"
    #         - "8084:8084"
    #         - "18083:18083"
            
    face:
        image: golang:1.16-stretch
        container_name: face
        restart: always
        ports:
            - "3570:3570"
            - "9081:9081"
        volumes:
            - ./:/opt
        working_dir: /opt
        command: go run bootface/main.go
        # command: ["/bin/sh", "-c", "while true;do echo hello docker;sleep 1;done"]

    park:
        image: golang:1.16-stretch
        container_name: park
        restart: always
        ports:
            - "9082:9082"
        volumes:
            - ./:/opt
        working_dir: /opt
        command: go run bootpark/main.go

    camera:
        image: golang:1.16-stretch
        container_name: camera
        restart: always
        ports:
            - "9085:9085"
        volumes:
            - ./:/opt
        working_dir: /opt
        command: go run bootcamera/main.go
