version: '3.1'
services:
    face:
        image: golang:1.16-stretch
        container_name: face
        restart: always
        ports:
            - "3570:3570"
            - "9081:9081"
        volumes:
            - ./:/opt
        working_dir: /opt
        command: go run face/main.go
        # command: ["/bin/sh", "-c", "while true;do echo hello docker;sleep 1;done"]