FROM registry.cn-hangzhou.aliyuncs.com/city-cloud/golang:1.15-1.0.1
LABEL maintainer="xyqbgn@126.com"

# COPY . .

# RUN go build -ldflags "-s -w" -o server main.go

# CMD ["./server"]
CMD ["/bin/sh","-c", " while true;do echo hello docker;sleep 1;done"]